(cl:defpackage panther_msgs-srv
  (:use )
  (:export
   "SETLEDANIMATION"
   "<SETLEDANIMATION-REQUEST>"
   "SETLEDANIMATION-REQUEST"
   "<SETLEDANIMATION-RESPONSE>"
   "SETLEDANIMATION-RESPONSE"
   "SETLEDBRIGHTNESS"
   "<SETLEDBRIGHTNESS-REQUEST>"
   "SETLEDBRIGHTNESS-REQUEST"
   "<SETLEDBRIGHTNESS-RESPONSE>"
   "SETLEDBRIGHTNESS-RESPONSE"
   "SETLEDIMAGEANIMATION"
   "<SETLEDIMAGEANIMATION-REQUEST>"
   "SETLEDIMAGEANIMATION-REQUEST"
   "<SETLEDIMAGEANIMATION-RESPONSE>"
   "SETLEDIMAGEANIMATION-RESPONSE"
  ))

