# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from panther_msgs/SetLEDImageAnimationRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import panther_msgs.msg

class SetLEDImageAnimationRequest(genpy.Message):
  _md5sum = "2fe9a29aafdecbd1db4304f1971b8337"
  _type = "panther_msgs/SetLEDImageAnimationRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """panther_msgs/LEDImageAnimation front
panther_msgs/LEDImageAnimation rear
bool repeating

================================================================================
MSG: panther_msgs/LEDImageAnimation
string image
float32 duration
float32 brightness
uint8 repeat
uint32 color"""
  __slots__ = ['front','rear','repeating']
  _slot_types = ['panther_msgs/LEDImageAnimation','panther_msgs/LEDImageAnimation','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       front,rear,repeating

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SetLEDImageAnimationRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.front is None:
        self.front = panther_msgs.msg.LEDImageAnimation()
      if self.rear is None:
        self.rear = panther_msgs.msg.LEDImageAnimation()
      if self.repeating is None:
        self.repeating = False
    else:
      self.front = panther_msgs.msg.LEDImageAnimation()
      self.rear = panther_msgs.msg.LEDImageAnimation()
      self.repeating = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.front.image
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2fBI().pack(_x.front.duration, _x.front.brightness, _x.front.repeat, _x.front.color))
      _x = self.rear.image
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2fBIB().pack(_x.rear.duration, _x.rear.brightness, _x.rear.repeat, _x.rear.color, _x.repeating))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.front is None:
        self.front = panther_msgs.msg.LEDImageAnimation()
      if self.rear is None:
        self.rear = panther_msgs.msg.LEDImageAnimation()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.front.image = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.front.image = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.front.duration, _x.front.brightness, _x.front.repeat, _x.front.color,) = _get_struct_2fBI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.rear.image = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.rear.image = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.rear.duration, _x.rear.brightness, _x.rear.repeat, _x.rear.color, _x.repeating,) = _get_struct_2fBIB().unpack(str[start:end])
      self.repeating = bool(self.repeating)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.front.image
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2fBI().pack(_x.front.duration, _x.front.brightness, _x.front.repeat, _x.front.color))
      _x = self.rear.image
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2fBIB().pack(_x.rear.duration, _x.rear.brightness, _x.rear.repeat, _x.rear.color, _x.repeating))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.front is None:
        self.front = panther_msgs.msg.LEDImageAnimation()
      if self.rear is None:
        self.rear = panther_msgs.msg.LEDImageAnimation()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.front.image = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.front.image = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.front.duration, _x.front.brightness, _x.front.repeat, _x.front.color,) = _get_struct_2fBI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.rear.image = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.rear.image = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.rear.duration, _x.rear.brightness, _x.rear.repeat, _x.rear.color, _x.repeating,) = _get_struct_2fBIB().unpack(str[start:end])
      self.repeating = bool(self.repeating)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2fBI = None
def _get_struct_2fBI():
    global _struct_2fBI
    if _struct_2fBI is None:
        _struct_2fBI = struct.Struct("<2fBI")
    return _struct_2fBI
_struct_2fBIB = None
def _get_struct_2fBIB():
    global _struct_2fBIB
    if _struct_2fBIB is None:
        _struct_2fBIB = struct.Struct("<2fBIB")
    return _struct_2fBIB
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from panther_msgs/SetLEDImageAnimationResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SetLEDImageAnimationResponse(genpy.Message):
  _md5sum = "937c9679a518e3a18d831e57125ea522"
  _type = "panther_msgs/SetLEDImageAnimationResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool success
string message
"""
  __slots__ = ['success','message']
  _slot_types = ['bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       success,message

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SetLEDImageAnimationResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.success is None:
        self.success = False
      if self.message is None:
        self.message = ''
    else:
      self.success = False
      self.message = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.success
      buff.write(_get_struct_B().pack(_x))
      _x = self.message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.success,) = _get_struct_B().unpack(str[start:end])
      self.success = bool(self.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.message = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.message = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.success
      buff.write(_get_struct_B().pack(_x))
      _x = self.message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.success,) = _get_struct_B().unpack(str[start:end])
      self.success = bool(self.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.message = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.message = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class SetLEDImageAnimation(object):
  _type          = 'panther_msgs/SetLEDImageAnimation'
  _md5sum = '160476792cabdd0ac4f8a13800bc7d59'
  _request_class  = SetLEDImageAnimationRequest
  _response_class = SetLEDImageAnimationResponse
