(cl:in-package panther_msgs-msg)
(cl:export '(CAN_NET_ERR-VAL
          CAN_NET_ERR
          OVERHEAT-VAL
          OVERHEAT
          OVERVOLTAGE-VAL
          OVERVOLTAGE
          UNDERVOLTAGE-VAL
          UNDERVOLTAGE
          SHORT_CIRCUIT-VAL
          SHORT_CIRCUIT
          EMERGENCY_STOP-VAL
          EMERGENCY_STOP
          MOTOR_OR_SENSOR_SETUP_FAULT-VAL
          MOTOR_OR_SENSOR_SETUP_FAULT
          MOSFET_FAILURE-VAL
          MOSFET_FAILURE
          DEFAULT_CONFIG_LOADED_AT_STARTUP-VAL
          DEFAULT_CONFIG_LOADED_AT_STARTUP
))