# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from panther_msgs/FaultFlag.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FaultFlag(genpy.Message):
  _md5sum = "5a07885f1bc8f54f267cfc6c4eab520b"
  _type = "panther_msgs/FaultFlag"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool can_net_err
bool overheat
bool overvoltage
bool undervoltage
bool short_circuit
bool emergency_stop
bool motor_or_sensor_setup_fault
bool mosfet_failure
bool default_config_loaded_at_startup"""
  __slots__ = ['can_net_err','overheat','overvoltage','undervoltage','short_circuit','emergency_stop','motor_or_sensor_setup_fault','mosfet_failure','default_config_loaded_at_startup']
  _slot_types = ['bool','bool','bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       can_net_err,overheat,overvoltage,undervoltage,short_circuit,emergency_stop,motor_or_sensor_setup_fault,mosfet_failure,default_config_loaded_at_startup

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FaultFlag, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.can_net_err is None:
        self.can_net_err = False
      if self.overheat is None:
        self.overheat = False
      if self.overvoltage is None:
        self.overvoltage = False
      if self.undervoltage is None:
        self.undervoltage = False
      if self.short_circuit is None:
        self.short_circuit = False
      if self.emergency_stop is None:
        self.emergency_stop = False
      if self.motor_or_sensor_setup_fault is None:
        self.motor_or_sensor_setup_fault = False
      if self.mosfet_failure is None:
        self.mosfet_failure = False
      if self.default_config_loaded_at_startup is None:
        self.default_config_loaded_at_startup = False
    else:
      self.can_net_err = False
      self.overheat = False
      self.overvoltage = False
      self.undervoltage = False
      self.short_circuit = False
      self.emergency_stop = False
      self.motor_or_sensor_setup_fault = False
      self.mosfet_failure = False
      self.default_config_loaded_at_startup = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9B().pack(_x.can_net_err, _x.overheat, _x.overvoltage, _x.undervoltage, _x.short_circuit, _x.emergency_stop, _x.motor_or_sensor_setup_fault, _x.mosfet_failure, _x.default_config_loaded_at_startup))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.can_net_err, _x.overheat, _x.overvoltage, _x.undervoltage, _x.short_circuit, _x.emergency_stop, _x.motor_or_sensor_setup_fault, _x.mosfet_failure, _x.default_config_loaded_at_startup,) = _get_struct_9B().unpack(str[start:end])
      self.can_net_err = bool(self.can_net_err)
      self.overheat = bool(self.overheat)
      self.overvoltage = bool(self.overvoltage)
      self.undervoltage = bool(self.undervoltage)
      self.short_circuit = bool(self.short_circuit)
      self.emergency_stop = bool(self.emergency_stop)
      self.motor_or_sensor_setup_fault = bool(self.motor_or_sensor_setup_fault)
      self.mosfet_failure = bool(self.mosfet_failure)
      self.default_config_loaded_at_startup = bool(self.default_config_loaded_at_startup)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9B().pack(_x.can_net_err, _x.overheat, _x.overvoltage, _x.undervoltage, _x.short_circuit, _x.emergency_stop, _x.motor_or_sensor_setup_fault, _x.mosfet_failure, _x.default_config_loaded_at_startup))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.can_net_err, _x.overheat, _x.overvoltage, _x.undervoltage, _x.short_circuit, _x.emergency_stop, _x.motor_or_sensor_setup_fault, _x.mosfet_failure, _x.default_config_loaded_at_startup,) = _get_struct_9B().unpack(str[start:end])
      self.can_net_err = bool(self.can_net_err)
      self.overheat = bool(self.overheat)
      self.overvoltage = bool(self.overvoltage)
      self.undervoltage = bool(self.undervoltage)
      self.short_circuit = bool(self.short_circuit)
      self.emergency_stop = bool(self.emergency_stop)
      self.motor_or_sensor_setup_fault = bool(self.motor_or_sensor_setup_fault)
      self.mosfet_failure = bool(self.mosfet_failure)
      self.default_config_loaded_at_startup = bool(self.default_config_loaded_at_startup)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9B = None
def _get_struct_9B():
    global _struct_9B
    if _struct_9B is None:
        _struct_9B = struct.Struct("<9B")
    return _struct_9B
