# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from panther_msgs/IOState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class IOState(genpy.Message):
  _md5sum = "9355949f9d224eb1c84d18ab411d0e55"
  _type = "panther_msgs/IOState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool aux_power
bool charger_connected
bool charger_enabled
bool digital_power
bool fan
bool motor_power
bool power_button"""
  __slots__ = ['aux_power','charger_connected','charger_enabled','digital_power','fan','motor_power','power_button']
  _slot_types = ['bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       aux_power,charger_connected,charger_enabled,digital_power,fan,motor_power,power_button

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IOState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.aux_power is None:
        self.aux_power = False
      if self.charger_connected is None:
        self.charger_connected = False
      if self.charger_enabled is None:
        self.charger_enabled = False
      if self.digital_power is None:
        self.digital_power = False
      if self.fan is None:
        self.fan = False
      if self.motor_power is None:
        self.motor_power = False
      if self.power_button is None:
        self.power_button = False
    else:
      self.aux_power = False
      self.charger_connected = False
      self.charger_enabled = False
      self.digital_power = False
      self.fan = False
      self.motor_power = False
      self.power_button = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7B().pack(_x.aux_power, _x.charger_connected, _x.charger_enabled, _x.digital_power, _x.fan, _x.motor_power, _x.power_button))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.aux_power, _x.charger_connected, _x.charger_enabled, _x.digital_power, _x.fan, _x.motor_power, _x.power_button,) = _get_struct_7B().unpack(str[start:end])
      self.aux_power = bool(self.aux_power)
      self.charger_connected = bool(self.charger_connected)
      self.charger_enabled = bool(self.charger_enabled)
      self.digital_power = bool(self.digital_power)
      self.fan = bool(self.fan)
      self.motor_power = bool(self.motor_power)
      self.power_button = bool(self.power_button)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7B().pack(_x.aux_power, _x.charger_connected, _x.charger_enabled, _x.digital_power, _x.fan, _x.motor_power, _x.power_button))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.aux_power, _x.charger_connected, _x.charger_enabled, _x.digital_power, _x.fan, _x.motor_power, _x.power_button,) = _get_struct_7B().unpack(str[start:end])
      self.aux_power = bool(self.aux_power)
      self.charger_connected = bool(self.charger_connected)
      self.charger_enabled = bool(self.charger_enabled)
      self.digital_power = bool(self.digital_power)
      self.fan = bool(self.fan)
      self.motor_power = bool(self.motor_power)
      self.power_button = bool(self.power_button)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7B = None
def _get_struct_7B():
    global _struct_7B
    if _struct_7B is None:
        _struct_7B = struct.Struct("<7B")
    return _struct_7B
