// Generated by gencpp from file panther_msgs/LEDAnimationQueue.msg
// DO NOT EDIT!


#ifndef PANTHER_MSGS_MESSAGE_LEDANIMATIONQUEUE_H
#define PANTHER_MSGS_MESSAGE_LEDANIMATIONQUEUE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panther_msgs
{
template <class ContainerAllocator>
struct LEDAnimationQueue_
{
  typedef LEDAnimationQueue_<ContainerAllocator> Type;

  LEDAnimationQueue_()
    : queue()  {
    }
  LEDAnimationQueue_(const ContainerAllocator& _alloc)
    : queue(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _queue_type;
  _queue_type queue;





  typedef boost::shared_ptr< ::panther_msgs::LEDAnimationQueue_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panther_msgs::LEDAnimationQueue_<ContainerAllocator> const> ConstPtr;

}; // struct LEDAnimationQueue_

typedef ::panther_msgs::LEDAnimationQueue_<std::allocator<void> > LEDAnimationQueue;

typedef boost::shared_ptr< ::panther_msgs::LEDAnimationQueue > LEDAnimationQueuePtr;
typedef boost::shared_ptr< ::panther_msgs::LEDAnimationQueue const> LEDAnimationQueueConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panther_msgs::LEDAnimationQueue_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panther_msgs::LEDAnimationQueue_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panther_msgs::LEDAnimationQueue_<ContainerAllocator1> & lhs, const ::panther_msgs::LEDAnimationQueue_<ContainerAllocator2> & rhs)
{
  return lhs.queue == rhs.queue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panther_msgs::LEDAnimationQueue_<ContainerAllocator1> & lhs, const ::panther_msgs::LEDAnimationQueue_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panther_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panther_msgs::LEDAnimationQueue_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panther_msgs::LEDAnimationQueue_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panther_msgs::LEDAnimationQueue_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panther_msgs::LEDAnimationQueue_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panther_msgs::LEDAnimationQueue_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panther_msgs::LEDAnimationQueue_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panther_msgs::LEDAnimationQueue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39f7d3ee4a5c2676f6070f72ebc81a53";
  }

  static const char* value(const ::panther_msgs::LEDAnimationQueue_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39f7d3ee4a5c2676ULL;
  static const uint64_t static_value2 = 0xf6070f72ebc81a53ULL;
};

template<class ContainerAllocator>
struct DataType< ::panther_msgs::LEDAnimationQueue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panther_msgs/LEDAnimationQueue";
  }

  static const char* value(const ::panther_msgs::LEDAnimationQueue_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panther_msgs::LEDAnimationQueue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] queue\n"
;
  }

  static const char* value(const ::panther_msgs::LEDAnimationQueue_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panther_msgs::LEDAnimationQueue_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.queue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LEDAnimationQueue_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panther_msgs::LEDAnimationQueue_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panther_msgs::LEDAnimationQueue_<ContainerAllocator>& v)
  {
    s << indent << "queue[]" << std::endl;
    for (size_t i = 0; i < v.queue.size(); ++i)
    {
      s << indent << "  queue[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.queue[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANTHER_MSGS_MESSAGE_LEDANIMATIONQUEUE_H
