// Generated by gencpp from file panther_msgs/SetLEDBrightness.msg
// DO NOT EDIT!


#ifndef PANTHER_MSGS_MESSAGE_SETLEDBRIGHTNESS_H
#define PANTHER_MSGS_MESSAGE_SETLEDBRIGHTNESS_H

#include <ros/service_traits.h>


#include <panther_msgs/SetLEDBrightnessRequest.h>
#include <panther_msgs/SetLEDBrightnessResponse.h>


namespace panther_msgs
{

struct SetLEDBrightness
{

typedef SetLEDBrightnessRequest Request;
typedef SetLEDBrightnessResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLEDBrightness
} // namespace panther_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panther_msgs::SetLEDBrightness > {
  static const char* value()
  {
    return "96fbe2a49585a736ad8b4a31afbaf099";
  }

  static const char* value(const ::panther_msgs::SetLEDBrightness&) { return value(); }
};

template<>
struct DataType< ::panther_msgs::SetLEDBrightness > {
  static const char* value()
  {
    return "panther_msgs/SetLEDBrightness";
  }

  static const char* value(const ::panther_msgs::SetLEDBrightness&) { return value(); }
};


// service_traits::MD5Sum< ::panther_msgs::SetLEDBrightnessRequest> should match
// service_traits::MD5Sum< ::panther_msgs::SetLEDBrightness >
template<>
struct MD5Sum< ::panther_msgs::SetLEDBrightnessRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panther_msgs::SetLEDBrightness >::value();
  }
  static const char* value(const ::panther_msgs::SetLEDBrightnessRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panther_msgs::SetLEDBrightnessRequest> should match
// service_traits::DataType< ::panther_msgs::SetLEDBrightness >
template<>
struct DataType< ::panther_msgs::SetLEDBrightnessRequest>
{
  static const char* value()
  {
    return DataType< ::panther_msgs::SetLEDBrightness >::value();
  }
  static const char* value(const ::panther_msgs::SetLEDBrightnessRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panther_msgs::SetLEDBrightnessResponse> should match
// service_traits::MD5Sum< ::panther_msgs::SetLEDBrightness >
template<>
struct MD5Sum< ::panther_msgs::SetLEDBrightnessResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panther_msgs::SetLEDBrightness >::value();
  }
  static const char* value(const ::panther_msgs::SetLEDBrightnessResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panther_msgs::SetLEDBrightnessResponse> should match
// service_traits::DataType< ::panther_msgs::SetLEDBrightness >
template<>
struct DataType< ::panther_msgs::SetLEDBrightnessResponse>
{
  static const char* value()
  {
    return DataType< ::panther_msgs::SetLEDBrightness >::value();
  }
  static const char* value(const ::panther_msgs::SetLEDBrightnessResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANTHER_MSGS_MESSAGE_SETLEDBRIGHTNESS_H
