// Generated by gencpp from file panther_msgs/SetLEDBrightnessResponse.msg
// DO NOT EDIT!


#ifndef PANTHER_MSGS_MESSAGE_SETLEDBRIGHTNESSRESPONSE_H
#define PANTHER_MSGS_MESSAGE_SETLEDBRIGHTNESSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panther_msgs
{
template <class ContainerAllocator>
struct SetLEDBrightnessResponse_
{
  typedef SetLEDBrightnessResponse_<ContainerAllocator> Type;

  SetLEDBrightnessResponse_()
    : success(false)
    , message()  {
    }
  SetLEDBrightnessResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetLEDBrightnessResponse_

typedef ::panther_msgs::SetLEDBrightnessResponse_<std::allocator<void> > SetLEDBrightnessResponse;

typedef boost::shared_ptr< ::panther_msgs::SetLEDBrightnessResponse > SetLEDBrightnessResponsePtr;
typedef boost::shared_ptr< ::panther_msgs::SetLEDBrightnessResponse const> SetLEDBrightnessResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator1> & lhs, const ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator1> & lhs, const ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panther_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panther_msgs/SetLEDBrightnessResponse";
  }

  static const char* value(const ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
;
  }

  static const char* value(const ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLEDBrightnessResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panther_msgs::SetLEDBrightnessResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANTHER_MSGS_MESSAGE_SETLEDBRIGHTNESSRESPONSE_H
