// Generated by gencpp from file panther_msgs/SetLEDAnimation.msg
// DO NOT EDIT!


#ifndef PANTHER_MSGS_MESSAGE_SETLEDANIMATION_H
#define PANTHER_MSGS_MESSAGE_SETLEDANIMATION_H

#include <ros/service_traits.h>


#include <panther_msgs/SetLEDAnimationRequest.h>
#include <panther_msgs/SetLEDAnimationResponse.h>


namespace panther_msgs
{

struct SetLEDAnimation
{

typedef SetLEDAnimationRequest Request;
typedef SetLEDAnimationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLEDAnimation
} // namespace panther_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panther_msgs::SetLEDAnimation > {
  static const char* value()
  {
    return "4051ed2a8439003711f44f890ff30ab8";
  }

  static const char* value(const ::panther_msgs::SetLEDAnimation&) { return value(); }
};

template<>
struct DataType< ::panther_msgs::SetLEDAnimation > {
  static const char* value()
  {
    return "panther_msgs/SetLEDAnimation";
  }

  static const char* value(const ::panther_msgs::SetLEDAnimation&) { return value(); }
};


// service_traits::MD5Sum< ::panther_msgs::SetLEDAnimationRequest> should match
// service_traits::MD5Sum< ::panther_msgs::SetLEDAnimation >
template<>
struct MD5Sum< ::panther_msgs::SetLEDAnimationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panther_msgs::SetLEDAnimation >::value();
  }
  static const char* value(const ::panther_msgs::SetLEDAnimationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panther_msgs::SetLEDAnimationRequest> should match
// service_traits::DataType< ::panther_msgs::SetLEDAnimation >
template<>
struct DataType< ::panther_msgs::SetLEDAnimationRequest>
{
  static const char* value()
  {
    return DataType< ::panther_msgs::SetLEDAnimation >::value();
  }
  static const char* value(const ::panther_msgs::SetLEDAnimationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panther_msgs::SetLEDAnimationResponse> should match
// service_traits::MD5Sum< ::panther_msgs::SetLEDAnimation >
template<>
struct MD5Sum< ::panther_msgs::SetLEDAnimationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panther_msgs::SetLEDAnimation >::value();
  }
  static const char* value(const ::panther_msgs::SetLEDAnimationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panther_msgs::SetLEDAnimationResponse> should match
// service_traits::DataType< ::panther_msgs::SetLEDAnimation >
template<>
struct DataType< ::panther_msgs::SetLEDAnimationResponse>
{
  static const char* value()
  {
    return DataType< ::panther_msgs::SetLEDAnimation >::value();
  }
  static const char* value(const ::panther_msgs::SetLEDAnimationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANTHER_MSGS_MESSAGE_SETLEDANIMATION_H
